name: test
on: ['push', 'pull_request']
jobs:
  test:
    name: Test on os ${{ matrix.os }} and perl ${{ matrix.perl-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.30'
          - '5.32'
          - '5.34'
        os: [ubuntu-latest, windows-latest, macos-latest]
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Show perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm -n --installdeps .
      - name: Run tests
        run: prove -lvr t
